/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedOperacaoRouteImport } from './routes/_authenticated/operacao'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated/comercial'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated/bi'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro.index'
import { Route as AuthenticatedComercialIndexRouteImport } from './routes/_authenticated/comercial.index'
import { Route as PropostaAceiteTokenRouteImport } from './routes/proposta.aceite.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicGithubWebhookRouteImport } from './routes/api/public/github-webhook'
import { Route as ApiPublicBiOperacaoRouteImport } from './routes/api/public/bi-operacao'
import { Route as ApiPublicBiKpisOperacaoRouteImport } from './routes/api/public/bi-kpis-operacao'
import { Route as ApiPublicBiKpisFinanceiroRouteImport } from './routes/api/public/bi-kpis-financeiro'
import { Route as ApiPublicBiKpisComercialRouteImport } from './routes/api/public/bi-kpis-comercial'
import { Route as ApiPublicBiFinanceiroRouteImport } from './routes/api/public/bi-financeiro'
import { Route as ApiPublicBiComercialRouteImport } from './routes/api/public/bi-comercial'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'
import { Route as AuthenticatedFinanceiroRapportRouteImport } from './routes/_authenticated/financeiro.rapport'
import { Route as AuthenticatedFinanceiroContasAReceberRouteImport } from './routes/_authenticated/financeiro.contas-a-receber'
import { Route as AuthenticatedFinanceiroContasAPagarRouteImport } from './routes/_authenticated/financeiro.contas-a-pagar'
import { Route as AuthenticatedFinanceiroCentralRouteImport } from './routes/_authenticated/financeiro.central'
import { Route as AuthenticatedFinanceiroCadastrosRouteImport } from './routes/_authenticated/financeiro.cadastros'
import { Route as AuthenticatedComercialPrecificacaoRouteImport } from './routes/_authenticated/comercial.precificacao'
import { Route as AuthenticatedComercialMapaAprovacaoRouteImport } from './routes/_authenticated/comercial.mapa-aprovacao'
import { Route as AuthenticatedComercialDevisRouteImport } from './routes/_authenticated/comercial.devis'
import { Route as AuthenticatedComercialClientesRouteImport } from './routes/_authenticated/comercial.clientes'
import { Route as AuthenticatedComercialAreasRouteImport } from './routes/_authenticated/comercial.areas'
import { Route as AuthenticatedAjudaComercialRouteImport } from './routes/_authenticated/ajuda_.comercial'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin_.api-keys'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicFluxorMonitorSplatRouteImport } from './routes/api/public/fluxor-monitor.$'
import { Route as AuthenticatedComercialDevisIdRouteImport } from './routes/_authenticated/comercial_.devis.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperacaoRoute = AuthenticatedOperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedComercialIndexRoute =
  AuthenticatedComercialIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const PropostaAceiteTokenRoute = PropostaAceiteTokenRouteImport.update({
  id: '/proposta/aceite/$token',
  path: '/proposta/aceite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGithubWebhookRoute = ApiPublicGithubWebhookRouteImport.update({
  id: '/api/public/github-webhook',
  path: '/api/public/github-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBiOperacaoRoute = ApiPublicBiOperacaoRouteImport.update({
  id: '/api/public/bi-operacao',
  path: '/api/public/bi-operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBiKpisOperacaoRoute = ApiPublicBiKpisOperacaoRouteImport.update({
  id: '/api/public/bi-kpis-operacao',
  path: '/api/public/bi-kpis-operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBiKpisFinanceiroRoute =
  ApiPublicBiKpisFinanceiroRouteImport.update({
    id: '/api/public/bi-kpis-financeiro',
    path: '/api/public/bi-kpis-financeiro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBiKpisComercialRoute =
  ApiPublicBiKpisComercialRouteImport.update({
    id: '/api/public/bi-kpis-comercial',
    path: '/api/public/bi-kpis-comercial',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBiFinanceiroRoute = ApiPublicBiFinanceiroRouteImport.update({
  id: '/api/public/bi-financeiro',
  path: '/api/public/bi-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBiComercialRoute = ApiPublicBiComercialRouteImport.update({
  id: '/api/public/bi-comercial',
  path: '/api/public/bi-comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFinanceiroRapportRoute =
  AuthenticatedFinanceiroRapportRouteImport.update({
    id: '/rapport',
    path: '/rapport',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroContasAReceberRoute =
  AuthenticatedFinanceiroContasAReceberRouteImport.update({
    id: '/contas-a-receber',
    path: '/contas-a-receber',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroContasAPagarRoute =
  AuthenticatedFinanceiroContasAPagarRouteImport.update({
    id: '/contas-a-pagar',
    path: '/contas-a-pagar',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroCentralRoute =
  AuthenticatedFinanceiroCentralRouteImport.update({
    id: '/central',
    path: '/central',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroCadastrosRoute =
  AuthenticatedFinanceiroCadastrosRouteImport.update({
    id: '/cadastros',
    path: '/cadastros',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedComercialPrecificacaoRoute =
  AuthenticatedComercialPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const AuthenticatedComercialMapaAprovacaoRoute =
  AuthenticatedComercialMapaAprovacaoRouteImport.update({
    id: '/mapa-aprovacao',
    path: '/mapa-aprovacao',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const AuthenticatedComercialDevisRoute =
  AuthenticatedComercialDevisRouteImport.update({
    id: '/devis',
    path: '/devis',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const AuthenticatedComercialClientesRoute =
  AuthenticatedComercialClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const AuthenticatedComercialAreasRoute =
  AuthenticatedComercialAreasRouteImport.update({
    id: '/areas',
    path: '/areas',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const AuthenticatedAjudaComercialRoute =
  AuthenticatedAjudaComercialRouteImport.update({
    id: '/ajuda_/comercial',
    path: '/ajuda/comercial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/admin_/api-keys',
    path: '/admin/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFluxorMonitorSplatRoute =
  ApiPublicFluxorMonitorSplatRouteImport.update({
    id: '/api/public/fluxor-monitor/$',
    path: '/api/public/fluxor-monitor/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedComercialDevisIdRoute =
  AuthenticatedComercialDevisIdRouteImport.update({
    id: '/comercial_/devis/$id',
    path: '/comercial/devis/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/bi': typeof AuthenticatedBiRoute
  '/comercial': typeof AuthenticatedComercialRouteWithChildren
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/gestao': typeof AuthenticatedGestaoRoute
  '/hub': typeof AuthenticatedHubRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/ajuda/comercial': typeof AuthenticatedAjudaComercialRoute
  '/comercial/areas': typeof AuthenticatedComercialAreasRoute
  '/comercial/clientes': typeof AuthenticatedComercialClientesRoute
  '/comercial/devis': typeof AuthenticatedComercialDevisRoute
  '/comercial/mapa-aprovacao': typeof AuthenticatedComercialMapaAprovacaoRoute
  '/comercial/precificacao': typeof AuthenticatedComercialPrecificacaoRoute
  '/financeiro/cadastros': typeof AuthenticatedFinanceiroCadastrosRoute
  '/financeiro/central': typeof AuthenticatedFinanceiroCentralRoute
  '/financeiro/contas-a-pagar': typeof AuthenticatedFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AuthenticatedFinanceiroContasAReceberRoute
  '/financeiro/rapport': typeof AuthenticatedFinanceiroRapportRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/bi-comercial': typeof ApiPublicBiComercialRoute
  '/api/public/bi-financeiro': typeof ApiPublicBiFinanceiroRoute
  '/api/public/bi-kpis-comercial': typeof ApiPublicBiKpisComercialRoute
  '/api/public/bi-kpis-financeiro': typeof ApiPublicBiKpisFinanceiroRoute
  '/api/public/bi-kpis-operacao': typeof ApiPublicBiKpisOperacaoRoute
  '/api/public/bi-operacao': typeof ApiPublicBiOperacaoRoute
  '/api/public/github-webhook': typeof ApiPublicGithubWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/proposta/aceite/$token': typeof PropostaAceiteTokenRoute
  '/comercial/': typeof AuthenticatedComercialIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/comercial/devis/$id': typeof AuthenticatedComercialDevisIdRoute
  '/api/public/fluxor-monitor/$': typeof ApiPublicFluxorMonitorSplatRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/bi': typeof AuthenticatedBiRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/hub': typeof AuthenticatedHubRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/ajuda/comercial': typeof AuthenticatedAjudaComercialRoute
  '/comercial/areas': typeof AuthenticatedComercialAreasRoute
  '/comercial/clientes': typeof AuthenticatedComercialClientesRoute
  '/comercial/devis': typeof AuthenticatedComercialDevisRoute
  '/comercial/mapa-aprovacao': typeof AuthenticatedComercialMapaAprovacaoRoute
  '/comercial/precificacao': typeof AuthenticatedComercialPrecificacaoRoute
  '/financeiro/cadastros': typeof AuthenticatedFinanceiroCadastrosRoute
  '/financeiro/central': typeof AuthenticatedFinanceiroCentralRoute
  '/financeiro/contas-a-pagar': typeof AuthenticatedFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AuthenticatedFinanceiroContasAReceberRoute
  '/financeiro/rapport': typeof AuthenticatedFinanceiroRapportRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/bi-comercial': typeof ApiPublicBiComercialRoute
  '/api/public/bi-financeiro': typeof ApiPublicBiFinanceiroRoute
  '/api/public/bi-kpis-comercial': typeof ApiPublicBiKpisComercialRoute
  '/api/public/bi-kpis-financeiro': typeof ApiPublicBiKpisFinanceiroRoute
  '/api/public/bi-kpis-operacao': typeof ApiPublicBiKpisOperacaoRoute
  '/api/public/bi-operacao': typeof ApiPublicBiOperacaoRoute
  '/api/public/github-webhook': typeof ApiPublicGithubWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/proposta/aceite/$token': typeof PropostaAceiteTokenRoute
  '/comercial': typeof AuthenticatedComercialIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/comercial/devis/$id': typeof AuthenticatedComercialDevisIdRoute
  '/api/public/fluxor-monitor/$': typeof ApiPublicFluxorMonitorSplatRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/bi': typeof AuthenticatedBiRoute
  '/_authenticated/comercial': typeof AuthenticatedComercialRouteWithChildren
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/gestao': typeof AuthenticatedGestaoRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/operacao': typeof AuthenticatedOperacaoRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin_/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/ajuda_/comercial': typeof AuthenticatedAjudaComercialRoute
  '/_authenticated/comercial/areas': typeof AuthenticatedComercialAreasRoute
  '/_authenticated/comercial/clientes': typeof AuthenticatedComercialClientesRoute
  '/_authenticated/comercial/devis': typeof AuthenticatedComercialDevisRoute
  '/_authenticated/comercial/mapa-aprovacao': typeof AuthenticatedComercialMapaAprovacaoRoute
  '/_authenticated/comercial/precificacao': typeof AuthenticatedComercialPrecificacaoRoute
  '/_authenticated/financeiro/cadastros': typeof AuthenticatedFinanceiroCadastrosRoute
  '/_authenticated/financeiro/central': typeof AuthenticatedFinanceiroCentralRoute
  '/_authenticated/financeiro/contas-a-pagar': typeof AuthenticatedFinanceiroContasAPagarRoute
  '/_authenticated/financeiro/contas-a-receber': typeof AuthenticatedFinanceiroContasAReceberRoute
  '/_authenticated/financeiro/rapport': typeof AuthenticatedFinanceiroRapportRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/bi-comercial': typeof ApiPublicBiComercialRoute
  '/api/public/bi-financeiro': typeof ApiPublicBiFinanceiroRoute
  '/api/public/bi-kpis-comercial': typeof ApiPublicBiKpisComercialRoute
  '/api/public/bi-kpis-financeiro': typeof ApiPublicBiKpisFinanceiroRoute
  '/api/public/bi-kpis-operacao': typeof ApiPublicBiKpisOperacaoRoute
  '/api/public/bi-operacao': typeof ApiPublicBiOperacaoRoute
  '/api/public/github-webhook': typeof ApiPublicGithubWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/proposta/aceite/$token': typeof PropostaAceiteTokenRoute
  '/_authenticated/comercial/': typeof AuthenticatedComercialIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/comercial_/devis/$id': typeof AuthenticatedComercialDevisIdRoute
  '/api/public/fluxor-monitor/$': typeof ApiPublicFluxorMonitorSplatRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/admin'
    | '/ajuda'
    | '/bi'
    | '/comercial'
    | '/conciliacao'
    | '/financeiro'
    | '/gestao'
    | '/hub'
    | '/mensagens'
    | '/operacao'
    | '/email/unsubscribe'
    | '/admin/api-keys'
    | '/ajuda/comercial'
    | '/comercial/areas'
    | '/comercial/clientes'
    | '/comercial/devis'
    | '/comercial/mapa-aprovacao'
    | '/comercial/precificacao'
    | '/financeiro/cadastros'
    | '/financeiro/central'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/rapport'
    | '/api/public/$'
    | '/api/public/bi-comercial'
    | '/api/public/bi-financeiro'
    | '/api/public/bi-kpis-comercial'
    | '/api/public/bi-kpis-financeiro'
    | '/api/public/bi-kpis-operacao'
    | '/api/public/bi-operacao'
    | '/api/public/github-webhook'
    | '/lovable/email/suppression'
    | '/proposta/aceite/$token'
    | '/comercial/'
    | '/financeiro/'
    | '/comercial/devis/$id'
    | '/api/public/fluxor-monitor/$'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/admin'
    | '/ajuda'
    | '/bi'
    | '/conciliacao'
    | '/gestao'
    | '/hub'
    | '/mensagens'
    | '/operacao'
    | '/email/unsubscribe'
    | '/admin/api-keys'
    | '/ajuda/comercial'
    | '/comercial/areas'
    | '/comercial/clientes'
    | '/comercial/devis'
    | '/comercial/mapa-aprovacao'
    | '/comercial/precificacao'
    | '/financeiro/cadastros'
    | '/financeiro/central'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/rapport'
    | '/api/public/$'
    | '/api/public/bi-comercial'
    | '/api/public/bi-financeiro'
    | '/api/public/bi-kpis-comercial'
    | '/api/public/bi-kpis-financeiro'
    | '/api/public/bi-kpis-operacao'
    | '/api/public/bi-operacao'
    | '/api/public/github-webhook'
    | '/lovable/email/suppression'
    | '/proposta/aceite/$token'
    | '/comercial'
    | '/financeiro'
    | '/comercial/devis/$id'
    | '/api/public/fluxor-monitor/$'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/ajuda'
    | '/_authenticated/bi'
    | '/_authenticated/comercial'
    | '/_authenticated/conciliacao'
    | '/_authenticated/financeiro'
    | '/_authenticated/gestao'
    | '/_authenticated/hub'
    | '/_authenticated/mensagens'
    | '/_authenticated/operacao'
    | '/email/unsubscribe'
    | '/_authenticated/admin_/api-keys'
    | '/_authenticated/ajuda_/comercial'
    | '/_authenticated/comercial/areas'
    | '/_authenticated/comercial/clientes'
    | '/_authenticated/comercial/devis'
    | '/_authenticated/comercial/mapa-aprovacao'
    | '/_authenticated/comercial/precificacao'
    | '/_authenticated/financeiro/cadastros'
    | '/_authenticated/financeiro/central'
    | '/_authenticated/financeiro/contas-a-pagar'
    | '/_authenticated/financeiro/contas-a-receber'
    | '/_authenticated/financeiro/rapport'
    | '/api/public/$'
    | '/api/public/bi-comercial'
    | '/api/public/bi-financeiro'
    | '/api/public/bi-kpis-comercial'
    | '/api/public/bi-kpis-financeiro'
    | '/api/public/bi-kpis-operacao'
    | '/api/public/bi-operacao'
    | '/api/public/github-webhook'
    | '/lovable/email/suppression'
    | '/proposta/aceite/$token'
    | '/_authenticated/comercial/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/comercial_/devis/$id'
    | '/api/public/fluxor-monitor/$'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
  ApiPublicBiComercialRoute: typeof ApiPublicBiComercialRoute
  ApiPublicBiFinanceiroRoute: typeof ApiPublicBiFinanceiroRoute
  ApiPublicBiKpisComercialRoute: typeof ApiPublicBiKpisComercialRoute
  ApiPublicBiKpisFinanceiroRoute: typeof ApiPublicBiKpisFinanceiroRoute
  ApiPublicBiKpisOperacaoRoute: typeof ApiPublicBiKpisOperacaoRoute
  ApiPublicBiOperacaoRoute: typeof ApiPublicBiOperacaoRoute
  ApiPublicGithubWebhookRoute: typeof ApiPublicGithubWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  PropostaAceiteTokenRoute: typeof PropostaAceiteTokenRoute
  ApiPublicFluxorMonitorSplatRoute: typeof ApiPublicFluxorMonitorSplatRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operacao': {
      id: '/_authenticated/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof AuthenticatedOperacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/comercial/': {
      id: '/_authenticated/comercial/'
      path: '/'
      fullPath: '/comercial/'
      preLoaderRoute: typeof AuthenticatedComercialIndexRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/proposta/aceite/$token': {
      id: '/proposta/aceite/$token'
      path: '/proposta/aceite/$token'
      fullPath: '/proposta/aceite/$token'
      preLoaderRoute: typeof PropostaAceiteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github-webhook': {
      id: '/api/public/github-webhook'
      path: '/api/public/github-webhook'
      fullPath: '/api/public/github-webhook'
      preLoaderRoute: typeof ApiPublicGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi-operacao': {
      id: '/api/public/bi-operacao'
      path: '/api/public/bi-operacao'
      fullPath: '/api/public/bi-operacao'
      preLoaderRoute: typeof ApiPublicBiOperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi-kpis-operacao': {
      id: '/api/public/bi-kpis-operacao'
      path: '/api/public/bi-kpis-operacao'
      fullPath: '/api/public/bi-kpis-operacao'
      preLoaderRoute: typeof ApiPublicBiKpisOperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi-kpis-financeiro': {
      id: '/api/public/bi-kpis-financeiro'
      path: '/api/public/bi-kpis-financeiro'
      fullPath: '/api/public/bi-kpis-financeiro'
      preLoaderRoute: typeof ApiPublicBiKpisFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi-kpis-comercial': {
      id: '/api/public/bi-kpis-comercial'
      path: '/api/public/bi-kpis-comercial'
      fullPath: '/api/public/bi-kpis-comercial'
      preLoaderRoute: typeof ApiPublicBiKpisComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi-financeiro': {
      id: '/api/public/bi-financeiro'
      path: '/api/public/bi-financeiro'
      fullPath: '/api/public/bi-financeiro'
      preLoaderRoute: typeof ApiPublicBiFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi-comercial': {
      id: '/api/public/bi-comercial'
      path: '/api/public/bi-comercial'
      fullPath: '/api/public/bi-comercial'
      preLoaderRoute: typeof ApiPublicBiComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/financeiro/rapport': {
      id: '/_authenticated/financeiro/rapport'
      path: '/rapport'
      fullPath: '/financeiro/rapport'
      preLoaderRoute: typeof AuthenticatedFinanceiroRapportRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/contas-a-receber': {
      id: '/_authenticated/financeiro/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/financeiro/contas-a-receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasAReceberRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/contas-a-pagar': {
      id: '/_authenticated/financeiro/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/financeiro/contas-a-pagar'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasAPagarRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/central': {
      id: '/_authenticated/financeiro/central'
      path: '/central'
      fullPath: '/financeiro/central'
      preLoaderRoute: typeof AuthenticatedFinanceiroCentralRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/cadastros': {
      id: '/_authenticated/financeiro/cadastros'
      path: '/cadastros'
      fullPath: '/financeiro/cadastros'
      preLoaderRoute: typeof AuthenticatedFinanceiroCadastrosRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/comercial/precificacao': {
      id: '/_authenticated/comercial/precificacao'
      path: '/precificacao'
      fullPath: '/comercial/precificacao'
      preLoaderRoute: typeof AuthenticatedComercialPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/_authenticated/comercial/mapa-aprovacao': {
      id: '/_authenticated/comercial/mapa-aprovacao'
      path: '/mapa-aprovacao'
      fullPath: '/comercial/mapa-aprovacao'
      preLoaderRoute: typeof AuthenticatedComercialMapaAprovacaoRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/_authenticated/comercial/devis': {
      id: '/_authenticated/comercial/devis'
      path: '/devis'
      fullPath: '/comercial/devis'
      preLoaderRoute: typeof AuthenticatedComercialDevisRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/_authenticated/comercial/clientes': {
      id: '/_authenticated/comercial/clientes'
      path: '/clientes'
      fullPath: '/comercial/clientes'
      preLoaderRoute: typeof AuthenticatedComercialClientesRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/_authenticated/comercial/areas': {
      id: '/_authenticated/comercial/areas'
      path: '/areas'
      fullPath: '/comercial/areas'
      preLoaderRoute: typeof AuthenticatedComercialAreasRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/_authenticated/ajuda_/comercial': {
      id: '/_authenticated/ajuda_/comercial'
      path: '/ajuda/comercial'
      fullPath: '/ajuda/comercial'
      preLoaderRoute: typeof AuthenticatedAjudaComercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/api-keys': {
      id: '/_authenticated/admin_/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fluxor-monitor/$': {
      id: '/api/public/fluxor-monitor/$'
      path: '/api/public/fluxor-monitor/$'
      fullPath: '/api/public/fluxor-monitor/$'
      preLoaderRoute: typeof ApiPublicFluxorMonitorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/comercial_/devis/$id': {
      id: '/_authenticated/comercial_/devis/$id'
      path: '/comercial/devis/$id'
      fullPath: '/comercial/devis/$id'
      preLoaderRoute: typeof AuthenticatedComercialDevisIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedComercialRouteChildren {
  AuthenticatedComercialAreasRoute: typeof AuthenticatedComercialAreasRoute
  AuthenticatedComercialClientesRoute: typeof AuthenticatedComercialClientesRoute
  AuthenticatedComercialDevisRoute: typeof AuthenticatedComercialDevisRoute
  AuthenticatedComercialMapaAprovacaoRoute: typeof AuthenticatedComercialMapaAprovacaoRoute
  AuthenticatedComercialPrecificacaoRoute: typeof AuthenticatedComercialPrecificacaoRoute
  AuthenticatedComercialIndexRoute: typeof AuthenticatedComercialIndexRoute
}

const AuthenticatedComercialRouteChildren: AuthenticatedComercialRouteChildren =
  {
    AuthenticatedComercialAreasRoute: AuthenticatedComercialAreasRoute,
    AuthenticatedComercialClientesRoute: AuthenticatedComercialClientesRoute,
    AuthenticatedComercialDevisRoute: AuthenticatedComercialDevisRoute,
    AuthenticatedComercialMapaAprovacaoRoute:
      AuthenticatedComercialMapaAprovacaoRoute,
    AuthenticatedComercialPrecificacaoRoute:
      AuthenticatedComercialPrecificacaoRoute,
    AuthenticatedComercialIndexRoute: AuthenticatedComercialIndexRoute,
  }

const AuthenticatedComercialRouteWithChildren =
  AuthenticatedComercialRoute._addFileChildren(
    AuthenticatedComercialRouteChildren,
  )

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroCadastrosRoute: typeof AuthenticatedFinanceiroCadastrosRoute
  AuthenticatedFinanceiroCentralRoute: typeof AuthenticatedFinanceiroCentralRoute
  AuthenticatedFinanceiroContasAPagarRoute: typeof AuthenticatedFinanceiroContasAPagarRoute
  AuthenticatedFinanceiroContasAReceberRoute: typeof AuthenticatedFinanceiroContasAReceberRoute
  AuthenticatedFinanceiroRapportRoute: typeof AuthenticatedFinanceiroRapportRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroCadastrosRoute:
      AuthenticatedFinanceiroCadastrosRoute,
    AuthenticatedFinanceiroCentralRoute: AuthenticatedFinanceiroCentralRoute,
    AuthenticatedFinanceiroContasAPagarRoute:
      AuthenticatedFinanceiroContasAPagarRoute,
    AuthenticatedFinanceiroContasAReceberRoute:
      AuthenticatedFinanceiroContasAReceberRoute,
    AuthenticatedFinanceiroRapportRoute: AuthenticatedFinanceiroRapportRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedBiRoute: typeof AuthenticatedBiRoute
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRouteWithChildren
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedOperacaoRoute: typeof AuthenticatedOperacaoRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAjudaComercialRoute: typeof AuthenticatedAjudaComercialRoute
  AuthenticatedComercialDevisIdRoute: typeof AuthenticatedComercialDevisIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedBiRoute: AuthenticatedBiRoute,
  AuthenticatedComercialRoute: AuthenticatedComercialRouteWithChildren,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedOperacaoRoute: AuthenticatedOperacaoRoute,
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAjudaComercialRoute: AuthenticatedAjudaComercialRoute,
  AuthenticatedComercialDevisIdRoute: AuthenticatedComercialDevisIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
  ApiPublicBiComercialRoute: ApiPublicBiComercialRoute,
  ApiPublicBiFinanceiroRoute: ApiPublicBiFinanceiroRoute,
  ApiPublicBiKpisComercialRoute: ApiPublicBiKpisComercialRoute,
  ApiPublicBiKpisFinanceiroRoute: ApiPublicBiKpisFinanceiroRoute,
  ApiPublicBiKpisOperacaoRoute: ApiPublicBiKpisOperacaoRoute,
  ApiPublicBiOperacaoRoute: ApiPublicBiOperacaoRoute,
  ApiPublicGithubWebhookRoute: ApiPublicGithubWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  PropostaAceiteTokenRoute: PropostaAceiteTokenRoute,
  ApiPublicFluxorMonitorSplatRoute: ApiPublicFluxorMonitorSplatRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
